sudo: false
language: java
jobs:
  include:
    - jdk: oraclejdk8
      install: true
      script: mvn -V -B clean verify
    - jdk: openjdk7
      install: true
      script: mvn -V -B clean verify -pl !zuchini-junit5
